type CadPart = {
  type: string;
  name?: string;
  width?: number;
  depth?: number;
  height?: number;
  radius?: number;
  operation?: string;
  position?: {
    x?: number;
    y?: number;
    z?: number;
  };
};

type CadJson = {
  object?: string;
  units?: string;
  parts?: CadPart[];
  material?: string;
};

function safeName(name: string | undefined, fallback: string) {
  return (name || fallback).replace(/[^a-zA-Z0-9_]/g, "_");
}

export function cadToFeatureScript(cad: CadJson) {
  const parts = cad.parts || [];

  const lines: string[] = [];

  lines.push("// Generated by PromptShape");
  lines.push(`// Object: ${cad.object || "Untitled CAD"}`);
  lines.push(`// Units: ${cad.units || "inch"}`);
  lines.push(`// Material: ${cad.material || "not specified"}`);
  lines.push("");
  lines.push("FeatureScript 2600;");
  lines.push("");
  lines.push("import(path : \"onshape/std/common.fs\", version : \"2600.0\");");
  lines.push("");
  lines.push("annotation { \"Feature Type Name\" : \"PromptShape Generated CAD\" }");
  lines.push("export const promptShapeGeneratedCAD = defineFeature(function(context is Context, id is Id, definition is map)");
  lines.push("    precondition");
  lines.push("    {");
  lines.push("    }");
  lines.push("    {");

  parts.forEach((part, index) => {
    const name = safeName(part.name, `part_${index + 1}`);
    const x = part.position?.x ?? 0;
    const y = part.position?.y ?? 0;
    const z = part.position?.z ?? 0;

    if (part.type === "box") {
      const w = part.width ?? 1;
      const d = part.depth ?? 1;
      const h = part.height ?? 1;

      lines.push("");
      lines.push(`        // Box: ${name}`);
      lines.push(`        opBox(context, id + "${name}", {`);
      lines.push(`            "corner1" : vector(${x - w / 2}, ${y - d / 2}, ${z - h / 2}) * inch,`);
      lines.push(`            "corner2" : vector(${x + w / 2}, ${y + d / 2}, ${z + h / 2}) * inch`);
      lines.push("        });");
    }

    if (part.type === "cylinder") {
      const r = part.radius ?? 0.25;
      const h = part.height ?? 1;
      const isSubtract = part.operation === "subtract";

      lines.push("");
      lines.push(`        // Cylinder ${isSubtract ? "hole" : "solid"}: ${name}`);
      lines.push(`        opCylinder(context, id + "${name}", {`);
      lines.push(`            "center" : vector(${x}, ${y}, ${z - h / 2}) * inch,`);
      lines.push(`            "axis" : vector(0, 0, 1),`);
      lines.push(`            "radius" : ${r} * inch,`);
      lines.push(`            "depth" : ${h} * inch`);
      lines.push("        });");

      if (isSubtract) {
        lines.push("");
        lines.push(`        // NOTE: ${name} is marked as subtract.`);
        lines.push("        // Real boolean subtraction will be added in the next step.");
      }
    }
  });

  lines.push("");
  lines.push("    });");

  return lines.join("\n");
}