type CadPart = any;
type CadJson = any;

function safeId(name: string | undefined, fallback: string) {
  return (name || fallback).replace(/[^a-zA-Z0-9_]/g, "_");
}

function num(value: number) {
  return Number(value.toFixed(4));
}

function unitName(units: string | undefined) {
  const u = String(units || "inch").toLowerCase();
  if (u === "mm" || u === "millimeter" || u === "millimeters") {
    return "millimeter";
  }
  return "inch";
}

function cylinderCenters(
  x: number,
  y: number,
  z: number,
  h: number,
  axis = "z",
  unit = "inch"
) {
  if (axis === "x") {
    return {
      top: `vector(${num(x + h / 2)}, ${num(y)}, ${num(z)}) * ${unit}`,
      bottom: `vector(${num(x - h / 2)}, ${num(y)}, ${num(z)}) * ${unit}`,
    };
  }

  if (axis === "y") {
    return {
      top: `vector(${num(x)}, ${num(y + h / 2)}, ${num(z)}) * ${unit}`,
      bottom: `vector(${num(x)}, ${num(y - h / 2)}, ${num(z)}) * ${unit}`,
    };
  }

  return {
    top: `vector(${num(x)}, ${num(y)}, ${num(z + h / 2)}) * ${unit}`,
    bottom: `vector(${num(x)}, ${num(y)}, ${num(z - h / 2)}) * ${unit}`,
  };
}

function addBox(
  lines: string[],
  id: string,
  x: number,
  y: number,
  z: number,
  w: number,
  d: number,
  h: number,
  unit: string
) {
  lines.push(`        fCuboid(context, id + "${id}", {`);
  lines.push(
    `            "corner1" : vector(${num(x - w / 2)}, ${num(y - d / 2)}, ${num(z - h / 2)}) * ${unit},`
  );
  lines.push(
    `            "corner2" : vector(${num(x + w / 2)}, ${num(y + d / 2)}, ${num(z + h / 2)}) * ${unit}`
  );
  lines.push("        });");
}

function addCylinder(
  lines: string[],
  id: string,
  x: number,
  y: number,
  z: number,
  radius: number,
  height: number,
  axis: string,
  unit: string
) {
  const centers = cylinderCenters(x, y, z, height, axis, unit);

  lines.push(`        fCylinder(context, id + "${id}", {`);
  lines.push(`            "topCenter" : ${centers.top},`);
  lines.push(`            "bottomCenter" : ${centers.bottom},`);
  lines.push(`            "radius" : ${num(radius)} * ${unit}`);
  lines.push("        });");
}

export function createFeatureStudioCode(cad: CadJson) {
  const parts: CadPart[] = cad.parts || [];
  const unit = unitName(cad.units);
  const lines: string[] = [];

  lines.push("FeatureScript 2737;");
  lines.push('import(path : "onshape/std/geometry.fs", version : "2737.0");');
  lines.push("");
  lines.push("// Generated by PromptShape");
  lines.push(`// Object: ${cad.object || "Untitled"}`);
  lines.push(`// Units: ${cad.units || "inch"}`);
  lines.push("");
  lines.push('annotation { "Feature Type Name" : "PromptShape CAD" }');
  lines.push(
    "export const promptShapeCAD = defineFeature(function(context is Context, id is Id, definition is map)"
  );
  lines.push("    precondition");
  lines.push("    {");
  lines.push("    }");
  lines.push("    {");

  if (parts.length === 0) {
    lines.push("");
    lines.push("        // Fallback body");
    addBox(lines, "fallback_body", 0, 0, 0, 2, 2, 1, unit);
  }

  parts.forEach((part, index) => {
    const name = safeId(part.name, `part_${index + 1}`);
    const x = part.position?.x ?? 0;
    const y = part.position?.y ?? 0;
    const z = part.position?.z ?? 0;

    lines.push("");
    lines.push(`        // ${part.type}: ${name}`);

    if (part.type === "hole" || part.operation === "subtract") {
      addCylinder(
        lines,
        `${name}_marker`,
        x,
        y,
        z,
        part.radius ?? 0.25,
        part.height ?? 1,
        part.orientation?.axis ?? "z",
        unit
      );
      return;
    }

    if (
      part.type === "box" ||
      part.type === "rib" ||
      part.type === "wedge" ||
      part.type === "airfoil"
    ) {
      addBox(
        lines,
        name,
        x,
        y,
        z,
        part.chord ?? part.width ?? 1,
        part.span ?? part.depth ?? 1,
        Math.max(0.08, part.thickness ?? part.height ?? 0.15),
        unit
      );
      return;
    }

    if (part.type === "cylinder" || part.type === "cone") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? (part.width ? part.width / 2 : 0.4),
        part.height ?? 1,
        part.orientation?.axis ?? "z",
        unit
      );
      return;
    }

    if (part.type === "wheel") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? 0.8,
        part.height ?? 0.55,
        part.orientation?.axis ?? "y",
        unit
      );

      addCylinder(
        lines,
        `${name}_rim`,
        x,
        y,
        z,
        (part.radius ?? 0.8) * 0.55,
        (part.height ?? 0.55) + 0.08,
        part.orientation?.axis ?? "y",
        unit
      );
      return;
    }

    if (part.type === "sphere") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? 0.5,
        (part.radius ?? 0.5) * 2,
        "z",
        unit
      );
      return;
    }

    if (part.type === "loft") {
      lines.push(
        "        // Loft skipped in FeatureScript for stability. Rendered in Three.js preview."
      );
      return;
    }
  });

  lines.push("");
  lines.push("    });");

  return lines.join("\n");
}