type CadPart = any;
type CadJson = any;

function safeId(name: string | undefined, fallback: string) {
  return (name || fallback).replace(/[^a-zA-Z0-9_]/g, "_");
}

function num(value: number) {
  return Number(value.toFixed(4));
}

function cylinderCenters(x: number, y: number, z: number, h: number, axis = "z") {
  if (axis === "x") {
    return {
      top: `vector(${num(x + h / 2)}, ${num(y)}, ${num(z)}) * inch`,
      bottom: `vector(${num(x - h / 2)}, ${num(y)}, ${num(z)}) * inch`,
    };
  }

  if (axis === "y") {
    return {
      top: `vector(${num(x)}, ${num(y + h / 2)}, ${num(z)}) * inch`,
      bottom: `vector(${num(x)}, ${num(y - h / 2)}, ${num(z)}) * inch`,
    };
  }

  return {
    top: `vector(${num(x)}, ${num(y)}, ${num(z + h / 2)}) * inch`,
    bottom: `vector(${num(x)}, ${num(y)}, ${num(z - h / 2)}) * inch`,
  };
}

function addBox(
  lines: string[],
  id: string,
  x: number,
  y: number,
  z: number,
  w: number,
  d: number,
  h: number
) {
  lines.push(`        fCuboid(context, id + "${id}", {`);
  lines.push(
    `            "corner1" : vector(${num(x - w / 2)}, ${num(y - d / 2)}, ${num(
      z - h / 2
    )}) * inch,`
  );
  lines.push(
    `            "corner2" : vector(${num(x + w / 2)}, ${num(y + d / 2)}, ${num(
      z + h / 2
    )}) * inch`
  );
  lines.push("        });");
}

function addCylinder(
  lines: string[],
  id: string,
  x: number,
  y: number,
  z: number,
  radius: number,
  height: number,
  axis = "z"
) {
  const centers = cylinderCenters(x, y, z, height, axis);

  lines.push(`        fCylinder(context, id + "${id}", {`);
  lines.push(`            "topCenter" : ${centers.top},`);
  lines.push(`            "bottomCenter" : ${centers.bottom},`);
  lines.push(`            "radius" : ${num(radius)} * inch`);
  lines.push("        });");
}

function addTriangularWedge(
  lines: string[],
  id: string,
  x: number,
  y: number,
  z: number,
  w: number,
  d: number,
  h: number
) {
  const x1 = num(x - w / 2);
  const x2 = num(x + w / 2);
  const z1 = num(z - h / 2);
  const z2 = num(z + h / 2);
  const yPlane = num(y - d / 2);

  lines.push("");
  lines.push(`        // True triangular wedge/gusset: ${id}`);
  lines.push(`        var ${id}_sketch = newSketchOnPlane(context, id + "${id}_sketch", {`);
  lines.push(
    `            "sketchPlane" : plane(vector(0, ${yPlane}, 0) * inch, vector(0, 1, 0))`
  );
  lines.push("        });");

  lines.push(`        skLineSegment(${id}_sketch, "a", {`);
  lines.push(`            "start" : vector(${x1}, ${z1}) * inch,`);
  lines.push(`            "end" : vector(${x2}, ${z1}) * inch`);
  lines.push("        });");

  lines.push(`        skLineSegment(${id}_sketch, "b", {`);
  lines.push(`            "start" : vector(${x2}, ${z1}) * inch,`);
  lines.push(`            "end" : vector(${x1}, ${z2}) * inch`);
  lines.push("        });");

  lines.push(`        skLineSegment(${id}_sketch, "c", {`);
  lines.push(`            "start" : vector(${x1}, ${z2}) * inch,`);
  lines.push(`            "end" : vector(${x1}, ${z1}) * inch`);
  lines.push("        });");

  lines.push(`        skSolve(${id}_sketch);`);

  lines.push(`        opExtrude(context, id + "${id}_extrude", {`);
  lines.push(
    `            "entities" : qSketchRegion(id + "${id}_sketch"),`
  );
  lines.push(`            "direction" : vector(0, 1, 0),`);
  lines.push(`            "endBound" : BoundingType.BLIND,`);
  lines.push(`            "depth" : ${num(d)} * inch`);
  lines.push("        });");
}

export function createFeatureStudioCode(cad: CadJson) {
  const parts: CadPart[] = cad.parts || [];
  const lines: string[] = [];

  lines.push("FeatureScript 2737;");
  lines.push('import(path : "onshape/std/geometry.fs", version : "2737.0");');
  lines.push("");
  lines.push("// Generated by PromptShape");
  lines.push(`// Object: ${cad.object || "Untitled"}`);
  lines.push("");
  lines.push('annotation { "Feature Type Name" : "PromptShape CAD" }');
  lines.push(
    "export const promptShapeCAD = defineFeature(function(context is Context, id is Id, definition is map)"
  );
  lines.push("    precondition");
  lines.push("    {");
  lines.push("    }");
  lines.push("    {");

  if (parts.length === 0) {
    addBox(lines, "fallback_body", 0, 0, 0, 2, 2, 1);
  }

  parts.forEach((part, index) => {
    if (part.type === "hole" || part.operation === "subtract") return;

    const name = safeId(part.name, `part_${index + 1}`);
    const x = part.position?.x ?? 0;
    const y = part.position?.y ?? 0;
    const z = part.position?.z ?? 0;

    lines.push("");
    lines.push(`        // ${part.type}: ${name}`);

    if (part.type === "box" || part.type === "rib") {
      addBox(
        lines,
        name,
        x,
        y,
        z,
        part.width ?? 1,
        part.depth ?? 1,
        part.height ?? 1
      );
    }

    if (part.type === "wedge") {
      addBox(
        lines,
        name,
        x,
        y,
        z,
        part.width ?? 2,
        part.depth ?? 0.25,
        part.height ?? 2
      );
    }

    if (part.type === "cylinder" || part.type === "cone") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? (part.width ? part.width / 2 : 0.4),
        part.height ?? 1,
        part.orientation?.axis ?? "z"
      );
    }

    if (part.type === "wheel") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? 0.8,
        part.height ?? 0.55,
        part.orientation?.axis ?? "y"
      );
      addCylinder(
        lines,
        `${name}_rim`,
        x,
        y,
        z,
        (part.radius ?? 0.8) * 0.55,
        (part.height ?? 0.55) + 0.08,
        part.orientation?.axis ?? "y"
      );
      addCylinder(
        lines,
        `${name}_hub`,
        x,
        y,
        z,
        (part.radius ?? 0.8) * 0.25,
        (part.height ?? 0.55) + 0.14,
        part.orientation?.axis ?? "y"
      );
    }

    if (part.type === "airfoil") {
      addBox(
        lines,
        name,
        x,
        y,
        z,
        part.chord ?? part.depth ?? 1,
        part.span ?? part.width ?? 4,
        Math.max(0.08, part.thickness ?? part.height ?? 0.15)
      );
    }

    if (part.type === "loft") {
      const sections = part.sections || [];

      sections.forEach((s: any, sectionIndex: number) => {
        addBox(
          lines,
          `${name}_section_${sectionIndex + 1}`,
          s.x ?? 0,
          s.y ?? 0,
          s.z ?? 0.4,
          0.75,
          Math.max(0.25, s.width ?? 1),
          Math.max(0.15, s.height ?? 0.4)
        );
      });
    }

    if (part.type === "sphere") {
      addCylinder(
        lines,
        name,
        x,
        y,
        z,
        part.radius ?? 0.5,
        (part.radius ?? 0.5) * 2,
        "z"
      );
    }
  });

  lines.push("");
  lines.push("    });");

  return lines.join("\n");
}